server:
  port: 8070
  servlet:
    context-path: /v1.0/
spring:
  application:
    name: proxy-name
    version: develop
    username: admin
    password: 12345
  sleuth:
     sampler:
        probability: 1
zuul:
   ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
   prefix: /api
   host:
     connect-timeout-millis: 100000
     socket-timeout-millis: 100000
   routes:
     dane:
        path: /dane/**
        url: https://co-mic-dane-ciudades.herokuapp.com/v1.0
policy:
  ratelimits:
    -  
      name: dane
      limit: 1000 #optional - request number limit per type
      quota: 10 #optional - request number limit per refresh interval window
      refresh-interval: 60 #optional - request time limit per refresh interval window (in seconds)
      type: user  #origin user
jwt:
  token:
    timeOut: 280000000
    secret: tokensecret   

google:
  analytics: UA-XXXXXX-1
  clientId: ID  

